import collections
import os

from stackebrandtcurves.refseq import RefSeq
from stackebrandtcurves.ssu import SearchApplication
from stackebrandtcurves.assembly import RefseqAssembly

DATA_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), "data")
ASSEMBLY_SUMMARY_FP = os.path.join(DATA_DIR, "muribaculum_assembly_summary.txt")
TEST_FASTA = os.path.join(DATA_DIR, "muribaculum.fasta")
TEST_ACCESSIONS = os.path.join(DATA_DIR, "muribaculum_accessions.txt")

MockAssembly = collections.namedtuple("Assembly", ["accession", "ssu_seqs"])

class MockRefSeq:
    data_dir = DATA_DIR
    def get_16S_seqs(self, assembly):
        return [
            ("seq1", "GCTCGCATCGAT"),
            ("seq2", "GCTCGCATCGAT"), # duplicate, will not be added
            ("seq3", "TGCTCAGTCGT"),
        ]

def test_search_seq():
    refseq = RefSeq(DATA_DIR)
    refseq.load_assemblies()
    refseq.load_seqs()
    db = SearchApplication(refseq)
    hits = db.search_seq(
        "lcl|NZ_CP015402.2_rrna_41", TEST_SEQ, min_pctid = 95.0)
    hits = list(hits)
    assert len(hits) == 11
    for hit in hits:
        print(hit.subject.accession)
    last_hit = hits[-1]
    assert last_hit.subject.accession == "GCF_016696845.1"

def test_exhaustive_search():
    refseq = RefSeq(DATA_DIR)
    refseq.load_assemblies()
    refseq.load_seqs()
    db = SearchApplication(refseq)
    hits = db.exhaustive_search(
        "lcl|NZ_CP015402.2_rrna_41", TEST_SEQ, min_pctid = 95.0)
    hits = list(hits)
    assert len(hits) == 11
    last_hit = hits[-1]
    assert last_hit.subject.accession == "GCF_016696845.1"


TEST_SEQ = (
    "ACAACGAAGAGTTTGATCCTGGCTCAGGATGAACGCTAGCGACAGGCCTAACACATGCAAGTCGAGGGGCAGCGGGGAGC"
    "GAAGCTTGCTTTGCTCCGCCGGCGACCGGCGCACGGGTGAGTAACGCGTATGCAACCTGCCCGTTTCAGCGGGATAACCC"
    "GGAGAAATCCGGCCTAATACCGCATGTGGCCGAGGGGGAGGCATCTTCTTTCGGCCAAAGGAGGCAACTCCGGAGACGGA"
    "TGGGCATGCGTGACATTAGCTTGTTGGCGGGGTAACGGCCCACCAAGGCGACGATGTCTAGGGGTTCTGAGAGGAAGGTC"
    "CCCCACACTGGTACTGAGACACGGACCAGACTCCTACGGGAGGCAGCAGTGAGGAATATTGGTCAATGGGCGAGAGCCTG"
    "AACCAGCCAAGTCGCGTGAAGGATGACGGCCCTACGGGTTGTAAACTTCTTTTGTCAGGGAGCAATTGAGTCCACGTGTG"
    "GGCTTAGCGAGAGTACCTGAAGAAAAAGCATCGGCTAACTCCGTGCCAGCAGCCGCGGTAATACGGAGGATGCGAGCGTT"
    "ATCCGGATTTATTGGGTTTAAAGGGTGCGTAGGCGGAATATCAAGTCAGCGGTAAAAATTCGGGGCTCAACCCCGTCGTG"
    "CCGTTGAAACTGATGTTCTTGAGTGGGCGAGAAGTATGCGGAATGCGTGGTGTAGCGGTGAAATGCATAGATATCACGCA"
    "GAACTCCGATTGCGAAGGCAGCATACCGGCGCCCAACTGACGCTGAAGCACGAAAGCGTGGGTATCGAACAGGATTAGAT"
    "ACCCTGGTAGTCCACGCAGTAAACGATGAATGCTAATTGTCCGGAGGGATTGACCTCTGGGTGATACAGCGAAAGCGTTA"
    "AGCATTCCACCTGGGGAGTACGCCGGCAACGGTGAAACTCAAAGGAATTGACGGGGGCCCGCACAAGCGGAGGAACATGT"
    "GGTTTAATTCGATGATACGCGAGGAACCTTACCCGGGCTCAAACGCAGGAGGAATACATTTGAAAGGGTGTAGCTCTACG"
    "GAGTCTTCTGCGAGGTGCTGCATGGTTGTCGTCAGCTCGTGCCGTGAGGTGTCGGCTTAAGTGCCATAACGAGCGCAACC"
    "CCTATCGACAGTTGCCAACAGGTTAAGCTGGGAACTCTGTCGAGACTGCCGGCGCAAGCTGAGAGGAAGGCGGGGATGAC"
    "GTCAAATCAGCACGGCCCTTACGTCCGGGGCGACACACGTGTTACAATGGCGGCCACAGCGGGAAGCCAGGCGGCGACGC"
    "CGAGCGGAACCCGAAAAGCCGTCTCAGTTCGGATTGGAGTCTGCAACCCGACTCCATGAAGCTGGATTCGCTAGTAATCG"
    "CGCATCAGCCACGGCGCGGTGAATACGTTCCCGGGCCTTGTACACACCGCCCGTCAAGCCATGGGAGCCGGGAGTGCCTG"
    "AAGTACGTGACCGCAAGGAGCGTCCTAGGGTAAGACCGGTGACTGGGGCTAAGTCGTAACAAGGTAGCCGTACCGGAAGG"
    "TGCGGCTGGAACACCTCCTTT"
)
